### ISSUE TITLE
New service for "E-mail Search / Check" category

### ISSUE THREAD

**Issue by LeakCheck** [Ph055a/OSINT_Collection#14]
Hi, I would like to add our service into "E-mail Search / E-mail Check" category. We have been working for 2.5 years, since this period we've collected about 7.5B entries from more than 3000 databases and this number is still growing. We provide API on any subscription (SLA 99.95%), integration with Telegram bot, notifications of new entries and allow search by e-mail, username, password, corporate domain name, hash. Officially registered as a company, using reliable hosting and payment providers.
Our website: https://leakcheck.net

**Comment by Ph055a** [comment]
Hello,
Unfortunately I cannot allow this to be added as it is a paid service. This collection is only for actionable sources of information with no paywall. However you might want to join osint.team and let everyone there know about your service and what it has to offer.

Thank you, and sorry for the delay.
